### ISSUE TITLE
about the translated article

### ISSUE THREAD

**Issue by suhanyujie** [FreeMasen/wiredforge-wasmer-plugin-code#2]
* Hello sir~
* I have translated one article for "wasmr-plugin",because i think it's pretty good.I hope to get your support for this.
* If you do not.I'll stop this.
* The url of the translated article is: https://github.com/suhanyujie/article-transfer-rs/blob/master/src/using_wasmer_for_plugins
* Thank you~

**Comment by FreeMasen** [comment]
Ohh wow, thank you so much for doing this!

I would be happy to either host the HTML version along-side the English version or link to your translation if you are hosting it elsewhere. 

If you have the time/energy I would be grateful for you to continue!
